services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
    volumes:
      - ./AI_Data/openwebui:/app/backend/data
    ports:
      - "${OPENWEBUI_PORT:-8081}:8080"

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    environment:
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
#      - ./AI_Data/searxng:/app/data
    ports:
      - "${SEARXNG_PORT:-8082}:8080"
